meta:
  name: Environment Example
  type: environment
cards:
  deck:
    - keywords: Ongoing
      name: Example Card 1
      text: Card text 1
      hp: 12
      artist: Art By Adam
      flavor: Test flavor
    - count: 2
      keywords: Oneshot
      name: Example Card 2
      text: Card text 2
